services:
  - type: web
    name: simulador-cartas
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py --host 0.0.0.0
    envVars:
      - key: SIMULADOR_UPDATE_PASSWORD
        sync: false
